//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBillingProject.Contabilidad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Contabilidad.WSXContabilidadSoap")]
    public interface WSXContabilidadSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TheBillingProject.Contabilidad.HelloWorldResponse HelloWorld(TheBillingProject.Contabilidad.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TheBillingProject.Contabilidad.HelloWorldResponse> HelloWorldAsync(TheBillingProject.Contabilidad.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Descripcion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarAsiento", ReplyAction="*")]
        TheBillingProject.Contabilidad.registrarAsientoResponse registrarAsiento(TheBillingProject.Contabilidad.registrarAsientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarAsiento", ReplyAction="*")]
        System.Threading.Tasks.Task<TheBillingProject.Contabilidad.registrarAsientoResponse> registrarAsientoAsync(TheBillingProject.Contabilidad.registrarAsientoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TheBillingProject.Contabilidad.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TheBillingProject.Contabilidad.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TheBillingProject.Contabilidad.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TheBillingProject.Contabilidad.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarAsientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarAsiento", Namespace="http://tempuri.org/", Order=0)]
        public TheBillingProject.Contabilidad.registrarAsientoRequestBody Body;
        
        public registrarAsientoRequest() {
        }
        
        public registrarAsientoRequest(TheBillingProject.Contabilidad.registrarAsientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarAsientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IdAuxiliar;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int CuentaDB;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CuentaCR;
        
        public registrarAsientoRequestBody() {
        }
        
        public registrarAsientoRequestBody(string Descripcion, int IdAuxiliar, double Monto, int CuentaDB, int CuentaCR) {
            this.Descripcion = Descripcion;
            this.IdAuxiliar = IdAuxiliar;
            this.Monto = Monto;
            this.CuentaDB = CuentaDB;
            this.CuentaCR = CuentaCR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarAsientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarAsientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TheBillingProject.Contabilidad.registrarAsientoResponseBody Body;
        
        public registrarAsientoResponse() {
        }
        
        public registrarAsientoResponse(TheBillingProject.Contabilidad.registrarAsientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarAsientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int registrarAsientoResult;
        
        public registrarAsientoResponseBody() {
        }
        
        public registrarAsientoResponseBody(int registrarAsientoResult) {
            this.registrarAsientoResult = registrarAsientoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSXContabilidadSoapChannel : TheBillingProject.Contabilidad.WSXContabilidadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSXContabilidadSoapClient : System.ServiceModel.ClientBase<TheBillingProject.Contabilidad.WSXContabilidadSoap>, TheBillingProject.Contabilidad.WSXContabilidadSoap {
        
        public WSXContabilidadSoapClient() {
        }
        
        public WSXContabilidadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSXContabilidadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSXContabilidadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSXContabilidadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TheBillingProject.Contabilidad.HelloWorldResponse TheBillingProject.Contabilidad.WSXContabilidadSoap.HelloWorld(TheBillingProject.Contabilidad.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TheBillingProject.Contabilidad.HelloWorldRequest inValue = new TheBillingProject.Contabilidad.HelloWorldRequest();
            inValue.Body = new TheBillingProject.Contabilidad.HelloWorldRequestBody();
            TheBillingProject.Contabilidad.HelloWorldResponse retVal = ((TheBillingProject.Contabilidad.WSXContabilidadSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TheBillingProject.Contabilidad.HelloWorldResponse> TheBillingProject.Contabilidad.WSXContabilidadSoap.HelloWorldAsync(TheBillingProject.Contabilidad.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TheBillingProject.Contabilidad.HelloWorldResponse> HelloWorldAsync() {
            TheBillingProject.Contabilidad.HelloWorldRequest inValue = new TheBillingProject.Contabilidad.HelloWorldRequest();
            inValue.Body = new TheBillingProject.Contabilidad.HelloWorldRequestBody();
            return ((TheBillingProject.Contabilidad.WSXContabilidadSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TheBillingProject.Contabilidad.registrarAsientoResponse TheBillingProject.Contabilidad.WSXContabilidadSoap.registrarAsiento(TheBillingProject.Contabilidad.registrarAsientoRequest request) {
            return base.Channel.registrarAsiento(request);
        }
        
        public int registrarAsiento(string Descripcion, int IdAuxiliar, double Monto, int CuentaDB, int CuentaCR) {
            TheBillingProject.Contabilidad.registrarAsientoRequest inValue = new TheBillingProject.Contabilidad.registrarAsientoRequest();
            inValue.Body = new TheBillingProject.Contabilidad.registrarAsientoRequestBody();
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.IdAuxiliar = IdAuxiliar;
            inValue.Body.Monto = Monto;
            inValue.Body.CuentaDB = CuentaDB;
            inValue.Body.CuentaCR = CuentaCR;
            TheBillingProject.Contabilidad.registrarAsientoResponse retVal = ((TheBillingProject.Contabilidad.WSXContabilidadSoap)(this)).registrarAsiento(inValue);
            return retVal.Body.registrarAsientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TheBillingProject.Contabilidad.registrarAsientoResponse> TheBillingProject.Contabilidad.WSXContabilidadSoap.registrarAsientoAsync(TheBillingProject.Contabilidad.registrarAsientoRequest request) {
            return base.Channel.registrarAsientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TheBillingProject.Contabilidad.registrarAsientoResponse> registrarAsientoAsync(string Descripcion, int IdAuxiliar, double Monto, int CuentaDB, int CuentaCR) {
            TheBillingProject.Contabilidad.registrarAsientoRequest inValue = new TheBillingProject.Contabilidad.registrarAsientoRequest();
            inValue.Body = new TheBillingProject.Contabilidad.registrarAsientoRequestBody();
            inValue.Body.Descripcion = Descripcion;
            inValue.Body.IdAuxiliar = IdAuxiliar;
            inValue.Body.Monto = Monto;
            inValue.Body.CuentaDB = CuentaDB;
            inValue.Body.CuentaCR = CuentaCR;
            return ((TheBillingProject.Contabilidad.WSXContabilidadSoap)(this)).registrarAsientoAsync(inValue);
        }
    }
}
